[package]
name = "yehorbolt_sql_parser"
version = "0.1.0"
description = "A simple SQL parser written in Rust."
repository = "https://github.com/yehorbolt/yehorbolt_sql_parser"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = "4.4.8"
pest = "2.7.5"
pest_derive = "2.7.5"
thiserror = "1.0.50"

